### ISSUE TITLE
Cards are empty after import from Ankiapp

### ISSUE THREAD

**Issue by yijisnhram** [abdnh/anki-copycat-importer#8]
Hello,
My friend who has Ankiapp sent me xml zips of the decks she made so that I can study them. However when I import the zips, all the cards come out empty. Here is one of the zips she sent, for reference : 

[_nergies.zip](https://github.com/abdnh/anki-copycat-importer/files/14805364/_nergies.zip)

She works on a Mac and I'm on Windows 10 (Anki Version ⁨23.12.1 (1a1d4d54)⁩) if that matters.

![Capture d’écran 2024-03-29 154837](https://github.com/abdnh/anki-copycat-importer/assets/165400858/abee08b3-3007-4805-88f5-ad9f5d1b501c)

Thank you :)

**Comment by abdnh** [comment]
Looks like they changed the XML structure a bit. I'll look into updating the add-on (hopefully next week).

**Comment by abdnh** [comment]
I just released a fix for this.

**Comment by yijisnhram** [comment]
Thank you so much!!
