### ISSUE TITLE
Cards are empty after imported from AnkiApp

### ISSUE THREAD

**Issue by lara123456785** [abdnh/anki-copycat-importer#9]
Hi I have tried to transfer my flashcards from AnkiApp to Anki using your add on. 
I used the zip function as I was able to export my decks from AnkiApp onto my macbook.
However, when I go to learn the flashcards on Anki it says they are all blank? 
I am not sure how else to overcome this problem?

**Comment by abdnh** [comment]
Replied to you on the forums.

**Comment by abdnh** [comment]
Just released an update that appears to work with your files.
